insert into sponsors (id, name, private, donation) values (1, 'Brakus LLC', false, '17973.06');
insert into sponsors (id, name, private, donation) values (2, 'Langworth-Quitzon', false, '13861.68');
insert into sponsors (id, name, private, donation) values (3, 'Stracke-Dibbert', false, '19800.78');
insert into sponsors (id, name, private, donation) values (4, 'Hirthe Inc', true, '12902.21');
insert into sponsors (id, name, private, donation) values (5, 'Ortiz-Zieme', false, '16639.04');
insert into sponsors (id, name, private, donation) values (6, 'Hudson-Hilll', true, '18868.47');
insert into sponsors (id, name, private, donation) values (7, 'Schuster Group', true, '11719.66');
insert into sponsors (id, name, private, donation) values (8, 'Wehner, Toy and Gleason', true, '18404.98');
insert into sponsors (id, name, private, donation) values (9, 'Marks Group', false, '10953.05');
insert into sponsors (id, name, private, donation) values (10, 'Hintz-Senger', false, '12554.31');
insert into sponsors (id, name, private, donation) values (11, 'Satterfield, Zulauf and O''Reilly', false, '12407.47');
insert into sponsors (id, name, private, donation) values (12, 'Braun-Von', false, '15986.84');
insert into sponsors (id, name, private, donation) values (13, 'Barrows-Strosin', true, '18802.37');
insert into sponsors (id, name, private, donation) values (14, 'Mohr, Beatty and Sporer', false, '19136.05');
insert into sponsors (id, name, private, donation) values (15, 'Reichert, Miller and Gusikowski', false, '10562.43');
insert into sponsors (id, name, private, donation) values (16, 'Rolfson-Jakubowski', false, '17821.91');
insert into sponsors (id, name, private, donation) values (17, 'Carroll and Sons', true, '11404.02');
insert into sponsors (id, name, private, donation) values (18, 'Shields, Heathcote and Hilpert', true, '15056.19');
insert into sponsors (id, name, private, donation) values (19, 'Halvorson and Sons', true, '17726.09');
insert into sponsors (id, name, private, donation) values (20, 'Herman and Sons', true, '17544.47');
insert into sponsors (id, name, private, donation) values (21, 'Roberts-Schimmel', true, '17688.69');
insert into sponsors (id, name, private, donation) values (22, 'Sauer, Hagenes and Pfeffer', true, '11280.41');
insert into sponsors (id, name, private, donation) values (23, 'Koepp, Fadel and Russel', true, '16420.17');
insert into sponsors (id, name, private, donation) values (24, 'Hagenes-Nitzsche', false, '12312.55');
insert into sponsors (id, name, private, donation) values (25, 'Casper and Sons', false, '10833.88');
insert into sponsors (id, name, private, donation) values (26, 'Lang-Okuneva', true, '13530.48');
insert into sponsors (id, name, private, donation) values (27, 'Heller, Klein and Batz', true, '18386.21');
insert into sponsors (id, name, private, donation) values (28, 'Smitham-Wolf', true, '16493.46');
insert into sponsors (id, name, private, donation) values (29, 'Fadel Inc', false, '15919.42');
insert into sponsors (id, name, private, donation) values (30, 'Morar, Fisher and Waelchi', false, '19864.77');
insert into sponsors (id, name, private, donation) values (31, 'Dickens-VonRueden', true, '13312.49');
insert into sponsors (id, name, private, donation) values (32, 'Huel-Hansen', false, '16878.83');
insert into sponsors (id, name, private, donation) values (33, 'Bode Inc', false, '13320.84');
insert into sponsors (id, name, private, donation) values (34, 'Kihn, Hodkiewicz and Kassulke', true, '10113.39');
insert into sponsors (id, name, private, donation) values (35, 'Hammes-Leffler', true, '16442.37');
insert into sponsors (id, name, private, donation) values (36, 'Bogisich-Murazik', true, '11253.34');
insert into sponsors (id, name, private, donation) values (37, 'Shanahan-Koelpin', true, '16459.33');
insert into sponsors (id, name, private, donation) values (38, 'Reichert LLC', true, '16259.62');
insert into sponsors (id, name, private, donation) values (39, 'Toy-Boyle', true, '15382.61');
insert into sponsors (id, name, private, donation) values (40, 'Goodwin Inc', false, '19125.53');
insert into sponsors (id, name, private, donation) values (41, 'Denesik-Zieme', true, '15624.55');
insert into sponsors (id, name, private, donation) values (42, 'Morar, Sporer and Okuneva', true, '12646.06');
insert into sponsors (id, name, private, donation) values (43, 'White, Cremin and Hirthe', false, '16735.54');
insert into sponsors (id, name, private, donation) values (44, 'Runte-Kozey', true, '18825.40');
insert into sponsors (id, name, private, donation) values (45, 'Beer, Paucek and Cruickshank', true, '15827.63');
insert into sponsors (id, name, private, donation) values (46, 'Runolfsson LLC', false, '10725.02');
insert into sponsors (id, name, private, donation) values (47, 'Corwin Inc', true, '19084.86');
insert into sponsors (id, name, private, donation) values (48, 'Tremblay-Senger', false, '11777.60');
insert into sponsors (id, name, private, donation) values (49, 'Rogahn Group', true, '10043.67');
insert into sponsors (id, name, private, donation) values (50, 'Ward and Sons', true, '19997.32');
