insert into teams (id, team_name, country) values (1, 'Zoolab', 'Brazil');
insert into teams (id, team_name, country) values (2, 'Regrant', 'United States');
insert into teams (id, team_name, country) values (3, 'Opela', 'Russia');
insert into teams (id, team_name, country) values (4, 'Alphazap', 'Russia');
insert into teams (id, team_name, country) values (5, 'Veribet', 'Russia');
insert into teams (id, team_name, country) values (6, 'Y-find', 'Tanzania');
insert into teams (id, team_name, country) values (7, 'Sub-Ex', 'Indonesia');
insert into teams (id, team_name, country) values (8, 'Daltfresh', 'China');
insert into teams (id, team_name, country) values (9, 'Bitchip', 'Thailand');
insert into teams (id, team_name, country) values (10, 'Ventosanzap', 'Indonesia');
insert into teams (id, team_name, country) values (11, 'Bamity', 'France');
insert into teams (id, team_name, country) values (12, 'Job', 'India');
insert into teams (id, team_name, country) values (13, 'Flexidy', 'Russia');
insert into teams (id, team_name, country) values (14, 'Matsoft', 'Mexico');
insert into teams (id, team_name, country) values (15, 'Asoka', 'Syria');
insert into teams (id, team_name, country) values (16, 'Span', 'Indonesia');
insert into teams (id, team_name, country) values (17, 'Voyatouch', 'Brazil');
insert into teams (id, team_name, country) values (18, 'Prodder', 'Canada');
insert into teams (id, team_name, country) values (19, 'Treeflex', 'Poland');
insert into teams (id, team_name, country) values (20, 'Daltfresh', 'Dominican Republic');
