insert into Teams (id, team_name, country) values (1, 'libero nullam sit amet', 'Indonesia');
insert into Teams (id, team_name, country) values (2, 'cubilia curae', 'United States');
insert into Teams (id, team_name, country) values (3, 'nulla pede ullamcorper', 'Brazil');
insert into Teams (id, team_name, country) values (4, 'quis turpis sed', 'Thailand');
insert into Teams (id, team_name, country) values (5, 'vestibulum ac est', 'Croatia');
insert into Teams (id, team_name, country) values (6, 'justo sit', 'France');
insert into Teams (id, team_name, country) values (7, 'dictumst morbi', 'Argentina');
insert into Teams (id, team_name, country) values (8, 'metus vitae', 'China');
insert into Teams (id, team_name, country) values (9, 'pulvinar sed', 'Indonesia');
insert into Teams (id, team_name, country) values (10, 'etiam vel', 'Ecuador');
insert into Teams (id, team_name, country) values (11, 'pede lobortis ligula sit', 'Russia');
insert into Teams (id, team_name, country) values (12, 'proin risus', 'Norway');
insert into Teams (id, team_name, country) values (13, 'sit amet', 'Dominican Republic');
insert into Teams (id, team_name, country) values (14, 'posuere cubilia', 'El Salvador');
insert into Teams (id, team_name, country) values (15, 'ipsum praesent', 'Guatemala');
insert into Teams (id, team_name, country) values (16, 'tincidunt ante vel', 'China');
insert into Teams (id, team_name, country) values (17, 'vulputate ut ultrices', 'Vietnam');
insert into Teams (id, team_name, country) values (18, 'justo eu massa donec', 'Brazil');
insert into Teams (id, team_name, country) values (19, 'justo in', 'China');
insert into Teams (id, team_name, country) values (20, 'libero ut', 'Ukraine');
insert into Teams (id, team_name, country) values (21, 'at nibh in', 'Greece');
